CDMSystem/Controllers/GuildController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CDMSystem.Dominio.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CDMSystem.Controllers
{
    //[Route("[Controller]")]
    public class GuildController : Controller
    {
        private readonly IGuildRepository _guildRepository;

        public GuildController(IGuildRepository guildRepository)
        {
            _guildRepository = guildRepository;
        }

        // GET: Guild
        public ActionResult Index()
        {
            var guildsDTO = _guildRepository.GetAll();

            return View("~/Views/Principal/Guild.cshtml", guildsDTO);
        }

        // GET: Guild/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Guild/Create
        public ActionResult Create()
        {
            return View("~/Views/Cadastro/GuildCadastro.cshtml");
        }

        // POST: Guild/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Models.Guild _guild)
        {
            try
            {
                Dominio.DTO.Guild guildDTO = new Dominio.DTO.Guild();
                guildDTO.NomeGuild = _guild.NomeGuild;
                guildDTO.DescricaoGuild = _guild.DescricaoGuild;

                _guildRepository.Incluid(guildDTO);

                Created("Guild/Create", guildDTO);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Guild/Edit/5
        public ActionResult Edit(int id)
        {
            var guildDTO = _guildRepository.GetbyId(id);

            return View("~/Views/Edicao/GuildEdicao.cshtml", guildDTO);
        }

        // POST: Guild/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Models.Guild _guild)
        {
            try
            {
                Dominio.DTO.Guild guildDTO = new Dominio.DTO.Guild();
                guildDTO.IdGuild = id;
                guildDTO.NomeGuild = _guild.NomeGuild;
                guildDTO.DescricaoGuild = _guild.DescricaoGuild;

                _guildRepository.Update(guildDTO);

                Created("Guild/Edit", guildDTO);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Guild/Delete/5
        public ActionResult Delete(int id)
        {
            Dominio.DTO.Guild guildDTO = new Dominio.DTO.Guild();
            guildDTO.IdGuild = id;
            _guildRepository.Remove(guildDTO);

            return RedirectToAction(nameof(Index));
        }
    }
}

CDMSystem/Views/Cadastro/GuildCadastro.cshtml
@{
    ViewData["Title"] = "Guild - Cadastro";
    Layout = "~/Views/Shared/_Cadastro.cshtml";
}

@model Guild

<form asp-action="Create" asp-controller="Guild" id="CadastroGuild" method="post">
    <div>
        @* Cadastro da Guild *@
        <label>Nome da Guild:</label>
        <input type="text" asp-for="NomeGuild" class="form-control" id="NomeGuild" />

        <br>

        <label>Descrição da Guild:</label>
        <textarea asp-for="DescricaoGuild" class="form-control" id="DescricaoGuild"></textarea>

        <br>

        <button type="submit" id="ConfirmarCadastroGuild" class="btn btn-dark">Cadastrar</button>
    </div>
</form>

CDMSystem/Views/Cadastro/PersonagemCadastro.cshtml
@{
    ViewData["Title"] = "Home Page";
    ViewData["Layout"] = "_Layout";
}

@model Personagem

<form>
    <div>
        @* Personagem *@
        <label>Nome</label>
        <input type="text" asp-for="NomePersonagem" id="Nome" />

        <br>

        <label>Level</label>
        <input type="text" asp-for="LevelPersonagem" id="Level" />

        <br>

        <label>Experiência</label>
        <input type="text" asp-for="ExpPersonagem" id="Exp" />

        <br>

        <label></label>
        <select></select>

        <br>

        <label></label>
        <select></select>

        <br>

        <label></label>
        <select></select>

        <br>

        <label></label>
        <select></select>

        <br>

        <label></label>
        <select></select>

        <br>

        @* Main Status *@
        <label>HP</label>
        <input type="text" id="Hp" />

        <br>

        <label>MP</label>
        <input type="text" id="Mp" />

        <br>

        <label>DMGF</label>
        <input type="text" id="Dmgf" />

        <br>

        <label>DMGM</label>
        <input type="text" id="Dmgm" />

        <br>

        <label>DEF</label>
        <input type="text" id="Def" />

        <br>

        <label>FUR</label>
        <input type="text" id="Fur" />

        <br>

        <label>DET</label>
        <input type="text" id="Det" />

        <br>

        <label>CRIT</label>
        <input type="text" id="Crit" />

        <br>

        <label>ACR</label>
        <input type="text" id="Acr" />
    </div>
</form>